name: Places of interest CI
on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["14"]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        env:
          NODE_ENV: "development"
          MAP_ACCESS_KEY: ${{ secrets.MAP_ACCESS_KEY }}
          GOOGLE_LOGIN_ID: ${{ secrets.GOOGLE_LOGIN_ID }}
          FACEBOOK_LOGIN_ID: ${{ secrets.FACEBOOK_LOGIN_ID }}
      - name: Telegram Action
        if: cancelled() == false
        uses: xinthink/action-telegram@v1.1
        with:
          botToken: ${{ secrets.TG_BOT_TOKEN_ID }}
          chatId: ${{ secrets.TG_CHAT_ID }}
          jobStatus: ${{ job.status }}
      - name: Install dependencies
        run: yarn install

      - name: Check lint
        run: npm run lint

      - name: Test
        run: yarn test-all
      - name: Build
        run: yarn build

      - name: Telegram Action
        if: cancelled() == false
        uses: xinthink/action-telegram@v1.1
        with:
          botToken: ${{ secrets.TG_BOT_TOKEN_ID }}
          chatId: ${{ secrets.TG_CHAT_ID }}
          jobStatus: ${{ job.status }}
